---
title: "Capstone Project Exploratoru Analysis"
author: "Steve Uzupis"
date: "2024-07-07"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

$$Enviroment Build$$

*Packages Load*
```{r package load}
# load packages

library(readr)               # load csv files
library(readxl)              # load excel files
library(dplyr)               # data manipulation
library(lubridate)           # date & time manipulation
library(ggplot2)             # data visualization
#library(tidyverse)          # collection of statistical packages, packages loaded individually
```
*Data load*
```{r data load}
# load data

all_sdoh_data <- read_csv("data/sdoh_data.csv")
#cdc_data <- read_csv("data/cdc_data.csv")        found better response data set
all_chr_data <- read_csv("data/chr_data.csv",
                     skip = 1)
```

$$Data Cleaning$$

*Initial data cleaning*
```{r cdc feature removal}
# remove unused features - not using

#cdc_data <- cdc_data %>% 
#  filter(Response == '65+') %>% 
#  select('LocationAbbr', 'LocationDesc', 'Data_Value', 'Number', 'WeightedNumber', 'StratificationCategory1', 'Stratification1', 'LocationID')
```

```{r sdoh feature cleaning 1}
# remove unwanted features, create calculated feature

sdoh_data <- all_sdoh_data %>% 
  select(#"YEAR", 
    "COUNTYFIPS", #"STATEFIPS", 
    "STATE", "COUNTY", "REGION", 
  #"TERRITORY", 
  "ACS_TOT_POP_WT", #"ACS_TOT_POP_US_ABOVE1", "ACS_TOT_POP_ABOVE5", "ACS_TOT_POP_ABOVE15", "ACS_TOT_POP_ABOVE16", "ACS_TOT_POP_16_19", "ACS_TOT_POP_ABOVE25", "ACS_TOT_CIVIL_POP_ABOVE18", "ACS_TOT_CIVIL_VET_POP_ABOVE25", "ACS_TOT_OWN_CHILD_BELOW17", "ACS_TOT_WORKER_NWFH", "ACS_TOT_WORKER_HH", "ACS_TOT_CIVILIAN_LABOR", "ACS_TOT_CIVIL_EMPLOY_POP", "ACS_TOT_POP_POV", "ACS_TOT_CIVIL_NONINST_POP_POV", "ACS_TOT_CIVIL_POP_POV", "ACS_TOT_GRANDCHILDREN_GP", "ACS_TOT_HU", "ACS_TOT_HH", 
  "ACS_AVG_HH_SIZE",# "ACS_TOT_CIVIL_NONINST_POP", "ACS_TOT_CIVIL_VET_POP", "ACS_PCT_CHILD_DISAB", "ACS_PCT_DISABLE", "ACS_PCT_NONVET_DISABLE_18_64", "ACS_PCT_VET_DISABLE_18_64", 
  "ACS_PCT_MALE", "ACS_PCT_FEMALE", #"ACS_PCT_CTZ_US_BORN", "ACS_PCT_CTZ_NONUS_BORN", "ACS_PCT_FOREIGN_BORN",
  "ACS_PCT_NON_CITIZEN", "ACS_PCT_CTZ_NATURALIZED", "ACS_PCT_CTZ_ABOVE18", #"ACS_PCT_NONCTN_1990", "ACS_PCT_NONCTN_1999", "ACS_PCT_NONCTN_2000", "ACS_PCT_NONCTN_2010", "ACS_PCT_API_LANG", 
  "ACS_PCT_ENGL_NOT_ALL", #"ACS_PCT_ENGL_NOT_WELL", "ACS_PCT_ENGL_VERY_WELL", "ACS_PCT_ENGL_WELL", "ACS_PCT_ENGLISH", "ACS_PCT_HH_LIMIT_ENGLISH", "ACS_PCT_OTH_EURP", "ACS_PCT_OTH_LANG", "ACS_PCT_SPANISH", "ACS_PCT_VET", "ACS_PCT_GULFWAR_1990_2001", "ACS_PCT_GULFWAR_2001", "ACS_PCT_GULFWAR_VIETNAM", "ACS_PCT_VIETNAM", "ACS_MEDIAN_AGE", "ACS_MEDIAN_AGE_MALE", "ACS_MEDIAN_AGE_FEMALE", "ACS_PCT_AGE_0_4", "ACS_PCT_AGE_5_9", "ACS_PCT_AGE_10_14", "ACS_PCT_AGE_15_17", "ACS_PCT_AGE_0_17", "ACS_PCT_AGE_18_29", "ACS_PCT_AGE_18_44", "ACS_PCT_AGE_30_44", "ACS_PCT_AGE_45_64", "ACS_PCT_AGE_50_64", "ACS_PCT_AGE_ABOVE65", "ACS_PCT_AGE_ABOVE80", 
  "ACS_PCT_AIAN", #"ACS_PCT_AIAN_FEMALE", "ACS_PCT_AIAN_NONHISP", 
  "ACS_PCT_ASIAN", #"ACS_PCT_ASIAN_FEMALE", "ACS_PCT_ASIAN_MALE", "ACS_PCT_ASIAN_NONHISP", 
  "ACS_PCT_BLACK", #"ACS_PCT_BLACK_FEMALE", "ACS_PCT_BLACK_MALE", "ACS_PCT_BLACK_NONHISP", #"ACS_PCT_HISP_FEMALE", "ACS_PCT_HISP_MALE",
  "ACS_PCT_HISPANIC", #"ACS_PCT_MULT_RACE", "ACS_PCT_MULT_RACE_FEMALE", "ACS_PCT_MULT_RACE_MALE", "ACS_PCT_MULT_RACE_NONHISP", "ACS_PCT_NHPI", "ACS_PCT_NHPI_FEMALE", "ACS_PCT_NHPI_MALE", "ACS_PCT_NHPI_NONHISP", "ACS_PCT_OTHER_FEMALE", "ACS_PCT_OTHER_MALE", "ACS_PCT_OTHER_NONHISP", 
  "ACS_PCT_OTHER_RACE", "ACS_PCT_WHITE", #"ACS_PCT_WHITE_FEMALE", "ACS_PCT_WHITE_MALE", "ACS_PCT_WHITE_NONHISP", "ACS_PCT_HOUSEHOLDER_WHITE", "ACS_PCT_HOUSEHOLDER_BLACK", "ACS_PCT_HOUSEHOLDER_AIAN", "ACS_PCT_HOUSEHOLDER_ASIAN", "ACS_PCT_HOUSEHOLDER_NHPI", "ACS_PCT_HOUSEHOLDER_OTHER", "ACS_PCT_HOUSEHOLDER_MULT", "ACS_PCT_AIAN_COMB", "ACS_PCT_ASIAN_COMB", "ACS_PCT_BLACK_COMB", "ACS_PCT_NHPI_COMB", "ACS_PCT_WHITE_COMB", 
  "ACS_PCT_CHILD_1FAM", "ACS_PCT_CHILDREN_GRANDPARENT", "ACS_PCT_GRANDP_RESPS_NO_P", "ACS_PCT_GRANDP_RESPS_P", #"ACS_PCT_GRANDP_NO_RESPS", "ACS_PCT_HH_KID_1PRNT", 
  "ACS_PCT_HH_NO_COMP_DEV", "ACS_PCT_HH_SMARTPHONE", #"ACS_PCT_HH_SMARTPHONE_ONLY", 
  "ACS_PCT_HH_TABLET", #"ACS_PCT_HH_TABLET_ONLY", 
  "ACS_PCT_HH_PC", #"ACS_PCT_HH_PC_ONLY", 
  "ACS_PCT_HH_OTHER_COMP", #"ACS_PCT_HH_OTHER_COMP_ONLY", 
  "ACS_PCT_HH_INTERNET", #"ACS_PCT_HH_INTERNET_NO_SUBS", "ACS_PCT_HH_BROADBAND", "ACS_PCT_HH_BROADBAND_ONLY", 
  "ACS_PCT_HH_BROADBAND_ANY", "ACS_PCT_HH_CELLULAR", #"ACS_PCT_HH_CELLULAR_ONLY", 
  "ACS_PCT_HH_NO_INTERNET", "ACS_PCT_HH_SAT_INTERNET", "ACS_PCT_HH_DIAL_INTERNET_ONLY", #"ACS_PCT_DIVORCED_F", "ACS_PCT_DIVORCED_M", "ACS_PCT_MARRIED_SP_AB_F", "ACS_PCT_MARRIED_SP_AB_M", "ACS_PCT_MARRIED_SP_PR_F", "ACS_PCT_MARRIED_SP_PR_M", "ACS_PCT_NVR_MARRIED_F", "ACS_PCT_NVR_MARRIED_M", "ACS_PCT_WIDOWED_F", "ACS_PCT_WIDOWED_M", "ACS_PCT_POP_SAME_SEX_UNMRD_P", "ACS_PCT_POP_SAME_SEX_SPOUSE", 
  "ACS_PCT_ADMIN", "ACS_PCT_ART", "ACS_PCT_CONSTRUCT", "ACS_PCT_EDUC", "ACS_PCT_FINANCE", "ACS_PCT_GOVT", "ACS_PCT_INFORM", "ACS_PCT_MANUFACT", "ACS_PCT_NATURE", "ACS_PCT_OTHER", "ACS_PCT_PROFESS", "ACS_PCT_PVT_NONPROFIT", #"ACS_PCT_PVT_PROFIT", 
  "ACS_PCT_RETAIL", "ACS_PCT_TRANSPORT", "ACS_PCT_WHOLESALE", #"ACS_PCT_WORK_RES_F", "ACS_PCT_WORK_RES_M", 
  "ACS_PCT_EMPLOYED", "ACS_PCT_UNEMPLOY", #"ACS_PCT_NOT_LABOR", "ACS_PCT_VET_UNEMPL_18_64", "ACS_PCT_VET_LABOR_FORCE_18_64", "ACS_PCT_ARMED_FORCES", 
  "ACS_GINI_INDEX", #"ACS_MDN_GRNDPRNT_NO_PRNT_INC", "ACS_MDN_GRNDPRNT_INC", "ACS_MEDIAN_HH_INC_AIAN", "ACS_MEDIAN_HH_INC_ASIAN" , "ACS_MEDIAN_HH_INC_BLACK", "ACS_MEDIAN_HH_INC_HISP", "ACS_MEDIAN_HH_INC_MULTI", "ACS_MEDIAN_HH_INC_NHPI", "ACS_MEDIAN_HH_INC_OTHER", "ACS_MEDIAN_HH_INC_WHITE", "ACS_MEDIAN_HH_INC", "ACS_MEDIAN_INC_F", "ACS_MEDIAN_INC_M", "ACS_MEDIAN_NONVET_INC", "ACS_MEDIAN_VET_INC", "ACS_PCT_INC50_ABOVE65", "ACS_PCT_INC50_BELOW17", "ACS_PCT_HEALTH_INC_BELOW137", "ACS_PCT_HEALTH_INC_138_199", "ACS_PCT_HEALTH_INC_200_399", "ACS_PCT_HEALTH_INC_ABOVE400", 
  "ACS_PCT_HH_INC_10000", "ACS_PCT_HH_INC_100000", "ACS_PCT_HH_INC_14999", "ACS_PCT_HH_INC_24999", "ACS_PCT_HH_INC_49999", "ACS_PCT_HH_INC_99999", #"ACS_PCT_INC50", "ACS_PCT_NONVET_POV_18_64", "ACS_PCT_VET_POV_18_64", "ACS_PCT_PERSON_INC_100_124", "ACS_PCT_PERSON_INC_125_199", "ACS_PCT_PERSON_INC_ABOVE200", "ACS_PCT_PERSON_INC_BELOW99", 
  "ACS_PER_CAPITA_INC", #"ACS_PCT_POV_AIAN", "ACS_PCT_POV_ASIAN", "ACS_PCT_POV_BLACK", "ACS_PCT_POV_HISPANIC", "ACS_PCT_POV_MULTI", "ACS_PCT_POV_NHPI", "ACS_PCT_POV_OTHER", "ACS_PCT_POV_WHITE", "ACS_PCT_HH_1FAM_FOOD_STMP", "ACS_PCT_HH_FOOD_STMP", "ACS_PCT_HH_PUB_ASSIST", "ACS_PCT_HH_FOOD_STMP_BLW_POV", "ACS_PCT_HH_NO_FD_STMP_BLW_POV", "ACS_PCT_COLLEGE_ASSOCIATE_DGR", "ACS_PCT_BACHELOR_DGR", "ACS_PCT_NO_WORK_NO_SCHL_16_19", "ACS_PCT_GRADUATE_DGR", "ACS_PCT_HS_GRADUATE", "ACS_PCT_LT_HS", "ACS_PCT_POSTHS_ED", "ACS_PCT_VET_BACHELOR", "ACS_PCT_VET_COLLEGE", "ACS_PCT_VET_HS", 
  "ACS_MEDIAN_HOME_VALUE", "ACS_MEDIAN_RENT", #"ACS_PCT_1UP_RENT_1ROOM", "ACS_PCT_1UP_OWNER_1ROOM", "ACS_PCT_1UP_PERS_1ROOM", "ACS_PCT_HH_1PERS", "ACS_PCT_10UNITS", "ACS_PCT_GRP_QRT", "ACS_PCT_HU_MOBILE_HOME", "ACS_PCT_OWNER_HU", "ACS_PCT_OWNER_HU_CHILD", "ACS_PCT_RENTER_HU", "ACS_PCT_RENTER_HU_ABOVE65", "ACS_PCT_RENTER_HU_CHILD", "ACS_PCT_RENTER_HU_COST_30PCT", "ACS_PCT_RENTER_HU_COST_50PCT", 
  "ACS_PCT_VACANT_HU", #"ACS_PCT_HU_NO_FUEL", "ACS_PCT_HU_UTILITY_GAS", "ACS_PCT_HU_BOT_TANK_LP_GAS", "ACS_PCT_HU_OIL", "ACS_PCT_HU_WOOD", "ACS_PCT_HU_COAL", "ACS_PCT_HU_OTHER", "ACS_PCT_HU_ELEC", "ACS_PCT_HU_SOLAR", "ACS_MDN_OWNER_COST_MORTGAGE", "ACS_MDN_OWNER_COST_NO_MORTG", #"ACS_PCT_OWNER_HU_COST_30PCT", "ACS_PCT_OWNER_HU_COST_50PCT", "ACS_MEDIAN_YEAR_BUILT", "ACS_PCT_HU_BUILT_1979", "ACS_PCT_HU_KITCHEN", "ACS_PCT_HU_PLUMBING", "ACS_PCT_IN_STATE_MOVE", "ACS_PCT_IN_COUNTY_MOVE", "ACS_PCT_DIF_STATE", "ACS_PCT_HH_ABOVE65", "ACS_PCT_HH_ALONE_ABOVE65", 
  "ACS_PCT_COMMT_15MIN", "ACS_PCT_COMMT_29MIN", "ACS_PCT_COMMT_59MIN", "ACS_PCT_COMMT_60MINUP", #"ACS_PCT_HU_NO_VEH", "ACS_PCT_WORK_NO_CAR", "ACS_PCT_DRIVE_2WORK", 
  "ACS_PCT_PUBL_TRANSIT", #"ACS_PCT_PUB_COMMT_15MIN", "ACS_PCT_PUB_COMMT_29MIN", "ACS_PCT_PUB_COMMT_59MIN", "ACS_PCT_PUB_COMMT_60MINUP","ACS_PCT_TAXICAB_2WORK", "ACS_PCT_WALK_2WORK", 
  "ACS_PCT_MEDICAID_ANY", #"ACS_PCT_MEDICAID_ANY_BELOW64", 
  "ACS_PCT_MEDICARE_ONLY", #"ACS_PCT_OTHER_INS", "ACS_PCT_PVT_EMPL_DRCT", "ACS_PCT_PVT_EMPL_DRCT_BELOW64", "ACS_PCT_PRIVATE_ANY", "ACS_PCT_PRIVATE_ANY_BELOW64", "ACS_PCT_PRIVATE_EMPL", "ACS_PCT_PRIVATE_EMPL_BELOW64", "ACS_PCT_PRIVATE_MDCR", "ACS_PCT_PRIVATE_MDCR_35_64", "ACS_PCT_PRIVATE_OTHER", "ACS_PCT_PRIVATE_OTHER_BELOW64", "ACS_PCT_PRIVATE_SELF", "ACS_PCT_PRIVATE_SELF_BELOW64", "ACS_PCT_PUBLIC_ONLY", "ACS_PCT_PUBLIC_OTHER", "ACS_PCT_PUBLIC_OTHER_BELOW64", "ACS_PCT_SELF_MDCR_ABOVE35", "ACS_PCT_TRICARE_VA", "ACS_PCT_TRICARE_VA_BELOW64", "ACS_PCT_UNINSURED", "ACS_PCT_UNINSURED_BELOW64", "AHRF_USDA_RUCC_2013", "AHRF_VET", "AHRF_VET_MALE", "AHRF_VET_FEMALE", "AHRF_UNEMPLOYED_RATE", "AHRF_DAYS_AIR_QLT", "AHRF_PCT_GOOD_AQ", "AHRF_TXC_SITE_NO_DATA", "AHRF_TXC_SITE_CNTRL", "AHRF_TXC_SITE_NO_CNTRL", "AHRF_HPSA_DENTIST", "AHRF_HPSA_MENTAL", "AHRF_HPSA_PRIM", "AHRF_MARKET_ENROL", "AHRF_MARKET_ENROL_NEW", "AHRF_MARKET_ENROL_ACTIVE", "AHRF_MARKET_ENROL_AUTO", "AHRF_MARKET_ENROL_150", "AHRF_MARKET_ENROL_200", "AHRF_MARKET_ENROL_250", "AHRF_MARKET_ENROL_300", "AHRF_MARKET_ENROL_400", "AHRF_MARKET_ENROL_OTHER", "AHRF_MARKET_ENROL_NO_ASST", "AHRF_PRESC_ENROLLMENT", "AHRF_PCT_PRESC_PEN", "AHRF_TOT_ADV_NURSES", 
  "AHRF_ADV_NURSES_RATE", #"AHRF_TOT_CLIN_NURSE_SPEC", 
  "AHRF_CLIN_NURSE_SPEC_RATE", #"AHRF_TOT_DENTISTS", 
  "AHRF_DENTISTS_RATE", #"AHRF_TOT_NURSE_ANESTH", 
  "AHRF_NURSE_ANESTH_RATE", #"AHRF_TOT_NURSE_MIDWIVES", 
  "AHRF_NURSE_MIDWIVES_RATE", #"AHRF_TOT_NURSE_PRACT", 
  "AHRF_NURSE_PRACT_RATE", #"AHRF_TOT_PHYSICIAN_ASSIST", 
  "AHRF_PHYSICIAN_ASSIST_RATE", #"AMFAR_SSP", 
  "AMFAR_SSP_RATE", #"AMFAR_TOT_MEDSAFAC",
  "AMFAR_MEDSAFAC_RATE", #"AMFAR_TOT_AMATFAC", "AMFAR_AMATFAC_RATE", "AMFAR_TOT_HCVTFAC", "AMFAR_HCVTFAC_RATE", "AMFAR_TOT_HIVHCVTFAC", "AMFAR_HIVHCVTFAC_RATE", "AMFAR_TOT_HIVTFAC", "AMFAR_HIVTFAC_RATE", "AMFAR_TOT_MEDAMATFAC", "AMFAR_MEDAMATFAC_RATE", "AMFAR_TOT_MEDHCVTFAC", "AMFAR_MEDHCVTFAC_RATE", "AMFAR_TOT_MEDHIVHCVTFAC", "AMFAR_MEDHIVHCVTFAC_RATE", "AMFAR_TOT_MEDHIVTFAC", "AMFAR_MEDHIVTFAC_RATE", "AMFAR_TOT_MEDMHFAC", "AMFAR_MEDMHFAC_RATE", "AMFAR_TOT_MHFAC", 
  "AMFAR_MHFAC_RATE", #"CAF_ADJ_COUNTY_1", "CAF_ADJ_COUNTY_2", "CAF_ADJ_COUNTY_3", "CAF_ADJ_COUNTY_4", "CAF_ADJ_COUNTY_5", "CAF_ADJ_COUNTY_6", "CAF_ADJ_COUNTY_7", "CAF_ADJ_COUNTY_8", "CAF_ADJ_COUNTY_9", "CAF_ADJ_COUNTY_10", "CAF_ADJ_COUNTY_11", "CAF_ADJ_COUNTY_12", "CAF_ADJ_COUNTY_13", "CAF_ADJ_COUNTY_14","CDCW_TOT_POPULATION", "CDCW_INJURY_DTH_RATE", "CDCW_TRANSPORT_DTH_RATE", "CDCW_SELFHARM_DTH_RATE", "CDCW_ASSAULT_DTH_RATE", "CDCW_MATERNAL_DTH_RATE", "CDCW_OPIOID_DTH_RATE", "CDCW_DRUG_DTH_RATE", 
  "CEN_AREALAND_SQM_COUNTY", "CEN_POPDENSITY_COUNTY", #"CHR_TOT_MENTAL_PROV", "CHR_MENTAL_PROV_RATE", "CHR_TOT_POPULATION", "MP_MEDICARE_ELIGIBLES", "MP_MEDICARE_ADVTG_ENROLLED", "MP_PCT_ADVTG_PEN", "NCHS_URCS_2006", "NCHS_URCS_2013", "NEPHTN_ARSENIC_MEAN_CSW", "NEPHTN_ARSENIC_MEAN_POP", "NEPHTN_PCT_ARSENIC_MCL_NOTDETECT", "NEPHTN_PCT_ARSENIC_MCL_LESS10", "NEPHTN_PCT_ARSENIC_MCL_GREATER10", 
  "NEPHTN_HEATIND_90", #"NEPHTN_HEATIND_95", "NEPHTN_HEATIND_100", "NEPHTN_HEATIND_105", "NEPHTN_MAXDROUGHT", "NEPHTN_NUMDROUGHT", "NEPHTN_TEMPERATURE_90", "NEPHTN_TEMPERATURE_95", "NEPHTN_TEMPERATURE_100", "NEPHTN_TEMPERATURE_105", "NHC_AVG_LIC_STAFF", "NHC_AVG_REP_NURSE_STAFF", "NHC_AVG_ADJ_NURSE_STAFF", "NHC_TOT_FACS", "NHC_FACS_RATE", 
  "EPAA_2NDMAX_CO_1HR", #"EPAA_2NDMAX_CO_8HR", 
  "EPAA_98PR_NO2_1HR", #"EPAA_MEAN_NO2_1HR", "EPAA_2NDMAX_O3_1HR", "EPAA_4THMAX_O3_8HR", 
  "EPAA_MAX_PB_3MON", #"EPAA_2NDMAX_PM10_24HR", "EPAA_MEAN_WTD_PM10", "EPAA_MEAN_WTD_PM25", 
  "EPAA_98PR_PM25_DAILY", "EPAA_99PR_SO2_1HR", #"EPAA_2NDMAX_SO2_24HR", "EPAA_MEAN_SO2_1HR", "NOAAC_AVG_TEMP_APR", "NOAAC_AVG_TEMP_AUG", "NOAAC_AVG_TEMP_DEC", "NOAAC_AVG_TEMP_FEB", "NOAAC_AVG_TEMP_JAN", "NOAAC_AVG_TEMP_JUL", "NOAAC_AVG_TEMP_JUN", "NOAAC_AVG_TEMP_MAR", "NOAAC_AVG_TEMP_MAY", "NOAAC_AVG_TEMP_NOV", "NOAAC_AVG_TEMP_OCT", "NOAAC_AVG_TEMP_SEP", "NOAAC_MAX_TEMP_APR", "NOAAC_MAX_TEMP_AUG", "NOAAC_MAX_TEMP_DEC", "NOAAC_MAX_TEMP_FEB", "NOAAC_MAX_TEMP_JAN", "NOAAC_MAX_TEMP_JUL", "NOAAC_MAX_TEMP_JUN", "NOAAC_MAX_TEMP_MAR", "NOAAC_MAX_TEMP_MAY", "NOAAC_MAX_TEMP_NOV", "NOAAC_MAX_TEMP_OCT", "NOAAC_MAX_TEMP_SEP", "NOAAC_MIN_TEMP_APR", "NOAAC_MIN_TEMP_AUG", "NOAAC_MIN_TEMP_DEC", "NOAAC_MIN_TEMP_FEB", "NOAAC_MIN_TEMP_JAN", "NOAAC_MIN_TEMP_JUL", "NOAAC_MIN_TEMP_JUN", "NOAAC_MIN_TEMP_MAR", "NOAAC_MIN_TEMP_MAY", "NOAAC_MIN_TEMP_NOV", "NOAAC_MIN_TEMP_OCT", "NOAAC_MIN_TEMP_SEP", "NOAAC_PRECIPITATION_APR", "NOAAC_PRECIPITATION_AUG", "NOAAC_PRECIPITATION_DEC", "NOAAC_PRECIPITATION_FEB", "NOAAC_PRECIPITATION_JAN", "NOAAC_PRECIPITATION_JUL", "NOAAC_PRECIPITATION_JUN", "NOAAC_PRECIPITATION_MAR", "NOAAC_PRECIPITATION_MAY", "NOAAC_PRECIPITATION_NOV", "NOAAC_PRECIPITATION_OCT", "NOAAC_PRECIPITATION_SEP", "NOAAS_PROPERTY_DAMAGE", "NOAAS_TOT_DEATHS_DIRECT", "NOAAS_TOT_DEATHS_INDIRECT", "NOAAS_TOT_INJURIES_DIRECT", "NOAAS_TOT_INJURIES_INDIRECT", "NOAAS_TOT_STORMEVENT", "NOAAS_TOT_TORNADO", "NOAAS_TOT_WIND", "NOAAS_TOT_HAIL", "NOAAS_TOT_HURRICANE_STORM", "NOAAS_TOT_FLOOD", "NOAAS_TOT_WILDFIRE", "NOAAS_TOT_HEAT_EVENTS", "NOAAS_TOT_DROUGHT", 
  "SAIPE_MEDIAN_HH_INCOME", "SAIPE_PCT_POV", #"SAIPE_PCT_POV_0_17", "SAIPE_PCT_POV_5_17", "SAIPE_TOT_POV", "SAIPE_TOT_POV_0_17", "SAIPE_TOT_POV_5_17", "WUSTL_AVG_PM25", "HHC_PCT_HHA_NURSING", "HHC_PCT_HHA_PHYS_THERAPY", "HHC_PCT_HHA_OCC_THERAPY", "HHC_PCT_HHA_SPEECH", "HHC_PCT_HHA_MEDICAL", "HHC_PCT_HHA_AIDE", "HIFLD_MEDIAN_DIST_UC", "HIFLD_MEAN_DIST_UC", "HIFLD_MIN_DIST_UC", "HIFLD_MAX_DIST_UC", "HIFLD_UC", "HIFLD_UC_RATE", "IHS_HEALTH_FACILITY", "IHS_HEALTH_FACILITY_RATE", "LTC_AVG_PCT_PRESSURE_ULCER", "LTC_PCT_RESD_BLACK", "LTC_PCT_RESD_HISPANIC", "LTC_PCT_RESD_WHITE", "LTC_AVG_AGE", "LTC_PCT_MULTI_FAC", "LTC_PCT_FOR_PROFIT", "LTC_AVG_ACUITY_INDEX", "LTC_TOT_BEDS", "LTC_TOT_BEDS_RATE",
  "LTC_AVG_OBS_REHOSP_RATE", "LTC_AVG_OBS_SUCCESSFUL_DISC_RATE", #"LTC_AVG_PCT_MEDICAID", "LTC_AVG_PCT_MEDICARE", "LTC_OCCUPANCY_RATE", "MGV_PCT_MEDICAID", "MGV_TOT_BEN_PART_A_B", "MGV_TOT_BEN_FFS", "MGV_PCT_BEN_FFS_WHITE",  "MGV_PCT_BEN_FFS_BLACK", "MGV_PCT_BEN_FFS_HISPANIC", "MGV_PER_CAPITA_ACTUAL_IP", 
  "MGV_PER_CAPITA_STD_IP", #"MGV_PER_CAPITA_ACTUAL_OP", 
  "MGV_PER_CAPITA_STD_OP", #"MGV_PER_CAPITA_ACTUAL_EM", 
  "MGV_PER_CAPITA_STD_EM", #"MGV_PER_CAPITA_ACTUAL_PA", 
  "MGV_PER_CAPITA_STD_PA", #"MGV_PER_CAPITA_ACTUAL_HC", 
  "MGV_PER_CAPITA_STD_HC", #"MMD_OVERALL_PQI_M_RATE", "MMD_OVERALL_PQI_F_RATE", "MMD_OVERALL_PQI_WHITE_RATE", "MMD_OVERALL_PQI_BLACK_RATE", "MMD_OVERALL_PQI_OTHER_RATE", "MMD_OVERALL_PQI_ASIAN_RATE", "MMD_OVERALL_PQI_HISP_RATE", "MMD_OVERALL_PQI_AIAN_RATE", "MMD_ACUTE_PQI_M_RATE", "MMD_ACUTE_PQI_F_RATE", "MMD_ACUTE_PQI_WHITE_RATE", "MMD_ACUTE_PQI_BLACK_RATE", "MMD_ACUTE_PQI_OTHER_RATE", "MMD_ACUTE_PQI_ASIAN_RATE", "MMD_ACUTE_PQI_HISP_RATE", "MMD_ACUTE_PQI_AIAN_RATE", "MMD_CHRONIC_PQI_M_RATE", "MMD_CHRONIC_PQI_F_RATE", "MMD_CHRONIC_PQI_WHITE_RATE", "MMD_CHRONIC_PQI_BLACK_RATE", "MMD_CHRONIC_PQI_OTHER_RATE", "MMD_CHRONIC_PQI_ASIAN_RATE", "MMD_CHRONIC_PQI_HISP_RATE", "MMD_CHRONIC_PQI_AIAN_RATE", "MMD_ED_VISITS_M_RATE", "MMD_ED_VISITS_F_RATE", "MMD_ED_VISITS_WHITE_RATE", "MMD_ED_VISITS_BLACK_RATE", "MMD_ED_VISITS_OTHER_RATE", "MMD_ED_VISITS_ASIAN_RATE", "MMD_ED_VISITS_HISP_RATE", "MMD_ED_VISITS_AIAN_RATE", "MMD_ED_VISITS_MED_RATE", "MMD_ED_VISITS_DUAL_RATE", "MMD_READM_M_RATE", "MMD_READM_F_RATE", "MMD_READM_WHITE_RATE", "MMD_READM_BLACK_RATE", "MMD_READM_OTHER_RATE", "MMD_READM_ASIAN_RATE", "MMD_READM_HISP_RATE", "MMD_READM_AIAN_RATE", "MMD_ANXIETY_DISD", "MMD_BIPOLAR_DISD", "MMD_DEPR_DISD", "MMD_PERSONALITY_DISD", "MMD_OUD_IND", "PC_PCT_MEDICARE_APPRVD_FULL_AMT", "PC_PCT_MCARE_MAY_ACPT_APPRVD_AMT", 
  "POS_MEDIAN_DIST_ED", #"POS_MEAN_DIST_ED", "POS_MIN_DIST_ED", "POS_MAX_DIST_ED", 
  "POS_MEDIAN_DIST_MEDSURG_ICU", #"POS_MEAN_DIST_MEDSURG_ICU", "POS_MIN_DIST_MEDSURG_ICU", "POS_MAX_DIST_MEDSURG_ICU", 
  "POS_MEDIAN_DIST_TRAUMA", #"POS_MEAN_DIST_TRAUMA", "POS_MIN_DIST_TRAUMA", "POS_MAX_DIST_TRAUMA", 
  "POS_MEDIAN_DIST_PED_ICU", #"POS_MEAN_DIST_PED_ICU", "POS_MIN_DIST_PED_ICU", "POS_MAX_DIST_PED_ICU", 
  "POS_MEDIAN_DIST_OBSTETRICS", #"POS_MEAN_DIST_OBSTETRICS", "POS_MIN_DIST_OBSTETRICS", "POS_MAX_DIST_OBSTETRICS", 
  "POS_MEDIAN_DIST_CLINIC", #"POS_MEAN_DIST_CLINIC", "POS_MIN_DIST_CLINIC", "POS_MAX_DIST_CLINIC", 
  "POS_MEDIAN_DIST_ALC", #"POS_MEAN_DIST_ALC", "POS_MIN_DIST_ALC", "POS_MAX_DIST_ALC", "POS_TOT_FQHC", "POS_FQHC_RATE", "POS_TOT_CMHC", "POS_CMHC_RATE", "POS_TOT_RHC", "POS_RHC_RATE", "POS_TOT_HHA", "POS_HHA_RATE", "POS_TOT_HOSPICE", "POS_HOSPICE_RATE", "POS_TOT_ASC", "POS_ASC_RATE", "POS_TOT_NF", "POS_NF_RATE", "POS_TOT_NF_BEDS", "POS_NF_BEDS_RATE", "POS_TOT_SNF", "POS_SNF_RATE", "POS_TOT_SNF_BEDS",  "POS_SNF_BEDS_RATE", "POS_TOT_HOSP_OBSTETRIC", "POS_HOSP_OBSTETRIC_RATE", "POS_TOT_HOSP_PED_ICU", "POS_HOSP_PED_ICU_RATE", "POS_TOT_HOSP_BURN", "POS_HOSP_BURN_RATE", "POS_TOT_HOSP_MEDSURG_ICU", "POS_HOSP_MEDSURG_ICU_RATE", "POS_TOT_HOSP_REHAB", "POS_HOSP_REHAB_RATE", "POS_TOT_HOSP_ALC", "POS_HOSP_ALC_RATE", "POS_TOT_HOSP_PSYCH", "POS_HOSP_PSYCH_RATE", "POS_TOT_HOSP_AMBULANCE", "POS_HOSP_AMBULANCE_RATE", "POS_TOT_HOSP_CHEMO", "POS_HOSP_CHEMO_RATE", "POS_TOT_HOSP_ED", "POS_HOSP_ED_RATE", "POS_PCT_HOSP_FOR_PROFIT", "POS_PCT_HOSP_NON_PROFIT", "POS_PCT_HOSP_GOV", "CEN_AIAN_NH_IND"
  ) %>% 
  mutate(percent_grandparents_as_guardians = ACS_PCT_CHILDREN_GRANDPARENT * ((ACS_PCT_GRANDP_RESPS_P + ACS_PCT_GRANDP_RESPS_NO_P)/100)) %>% 
  select(-ACS_PCT_GRANDP_RESPS_P, -ACS_PCT_GRANDP_RESPS_NO_P, -ACS_PCT_CHILDREN_GRANDPARENT)
```

```{r sdoh feature renaming}
sdoh_data <- sdoh_data %>% 
  rename("fips_code" = "COUNTYFIPS",
         "state" = "STATE",
         "county" = "COUNTY",
         "region" = "REGION",
         "weighted_population"  = "ACS_TOT_POP_WT",
         "average_hh_size" = "ACS_AVG_HH_SIZE",
         "pct_male"  = "ACS_PCT_MALE",
         "pct_female" = "ACS_PCT_FEMALE",
         "pct_not_citizens" = "ACS_PCT_NON_CITIZEN",
         "pct_naturalized_citizens" = "ACS_PCT_CTZ_NATURALIZED",
         "pct_adult_citizens" = "ACS_PCT_CTZ_ABOVE18",
         "pct_no_english_spoken" = "ACS_PCT_ENGL_NOT_ALL",
         "pct_native_american" = "ACS_PCT_AIAN",
         "pct_asian" = "ACS_PCT_ASIAN",
         "pct_black" = "ACS_PCT_BLACK",
         "pct_hispanic" = "ACS_PCT_HISPANIC",
         "pct_other_race" = "ACS_PCT_OTHER_RACE",
         "pct_white" = "ACS_PCT_WHITE",
         "pct_single_parent" = "ACS_PCT_CHILD_1FAM",
         "pct_hh_no_computing_device" = "ACS_PCT_HH_NO_COMP_DEV",
         "pct_hh_smartphone" = "ACS_PCT_HH_SMARTPHONE",
         "pct_hh_tablet" = "ACS_PCT_HH_TABLET",
         "pct_hh_computer" = "ACS_PCT_HH_PC",
         "pct_hh_other_computer" = "ACS_PCT_HH_OTHER_COMP",
         "pct_hh_internet" = "ACS_PCT_HH_INTERNET",
         "pct_hh_broadband" = "ACS_PCT_HH_BROADBAND_ANY",
         "pct_hh_cell_data" = "ACS_PCT_HH_CELLULAR",
         "pct_hh_no_internet" = "ACS_PCT_HH_NO_INTERNET",
         "pct_hh_satellite" =  "ACS_PCT_HH_SAT_INTERNET",
         "pct_hh_dial_up" = "ACS_PCT_HH_DIAL_INTERNET_ONLY",
         "pct_employed_admin" = "ACS_PCT_ADMIN",
         "pct_employed_arts" = "ACS_PCT_ART", 
         "pct_employed_construction" = "ACS_PCT_CONSTRUCT",
         "pct_employed_education" = "ACS_PCT_EDUC",
         "pct_employed_finance" = "ACS_PCT_FINANCE",
         "pct_employed_government" = "ACS_PCT_GOVT",
         "pct_employed_information" = "ACS_PCT_INFORM",
         "pct_employed_manufacturing" = "ACS_PCT_MANUFACT",
         "pct_employed_nature" = "ACS_PCT_NATURE",
         "pct_employed_other" = "ACS_PCT_OTHER",
         "pct_employed_professional" = "ACS_PCT_PROFESS",
         "pct_employed_nonprofit" = "ACS_PCT_PVT_NONPROFIT",
         "pct_employed_retail" = "ACS_PCT_RETAIL",
         "pct_employed_transportation" = "ACS_PCT_TRANSPORT",
         "pct_employed_wholesale" = "ACS_PCT_WHOLESALE",
         "pct_employed" = "ACS_PCT_EMPLOYED",
         "pct_unemployed" = "ACS_PCT_UNEMPLOY",
         "gini_index" = "ACS_GINI_INDEX",
         "pct_hh_inc_10,000" = "ACS_PCT_HH_INC_10000",
         "pct_hh_inc_100,000" = "ACS_PCT_HH_INC_100000",
         "pct_hh_inc_14,999" = "ACS_PCT_HH_INC_14999",
         "pct_hh_inc_24,999" = "ACS_PCT_HH_INC_24999",
         "pct_hh_inc_49,999" = "ACS_PCT_HH_INC_49999",
         "pct_hh_inc_99,999" = "ACS_PCT_HH_INC_99999",
         "per_capita_income" = "ACS_PER_CAPITA_INC",
         "median_home_value" = "ACS_MEDIAN_HOME_VALUE",
         "median_rent" = "ACS_MEDIAN_RENT",
         "pct_houses_vacant" = "ACS_PCT_VACANT_HU",
         "pct_15_min_commute" = "ACS_PCT_COMMT_15MIN",
         "pct_29_min_commute" = "ACS_PCT_COMMT_29MIN",
         "pct_59_min_commute" = "ACS_PCT_COMMT_59MIN",
         "pct_60_min_plus_commute" = "ACS_PCT_COMMT_60MINUP",
         "pct_public_transportatin" = "ACS_PCT_PUBL_TRANSIT",
         "pct_w/_medicaid" = "ACS_PCT_MEDICAID_ANY",
         "pct_w/medicare" = "ACS_PCT_MEDICARE_ONLY",
         "adv_practice_nurse_pt" = "AHRF_ADV_NURSES_RATE",
         "clinical_nurse_pt" = "AHRF_CLIN_NURSE_SPEC_RATE",
         "dentist_pt" = "AHRF_DENTISTS_RATE",
         "anesthetist_nurse_pt" = "AHRF_NURSE_ANESTH_RATE",
         "midwife_pt" = "AHRF_NURSE_MIDWIVES_RATE",
         "nurse_practitioner_pt" = "AHRF_NURSE_PRACT_RATE",
         "pa_pt" = "AHRF_PHYSICIAN_ASSIST_RATE",
         "syringe_exchange_pt" = "AMFAR_SSP_RATE",
         "substance_abuse_facility_pt" = "AMFAR_MEDSAFAC_RATE",
         "mental_health_faciliy_pt" = "AMFAR_MHFAC_RATE",
         "land_area_sqm" = "CEN_AREALAND_SQM_COUNTY",
         "population_density" = "CEN_POPDENSITY_COUNTY",
         "days_over_90_f" = "NEPHTN_HEATIND_90",
         "co_measure" = "EPAA_2NDMAX_CO_1HR",
         "no2_measure" = "EPAA_98PR_NO2_1HR",
         "pb_measure" = "EPAA_MAX_PB_3MON",
         "pm_2.5_measure" = "EPAA_98PR_PM25_DAILY",
         "so2_measure" = "EPAA_99PR_SO2_1HR",
         "median_hh_income" = "SAIPE_MEDIAN_HH_INCOME",
         "pct_people_in_poverty" = "SAIPE_PCT_POV",
         "rehospitalization_rate" = "LTC_AVG_OBS_REHOSP_RATE",
         "successful_discharge_rate" = "LTC_AVG_OBS_SUCCESSFUL_DISC_RATE",
         "medicare_inpatient_payment" = "MGV_PER_CAPITA_STD_IP",
         "medicare_outpatient_payment" = "MGV_PER_CAPITA_STD_OP",
         "medicare_e&m_payment" = "MGV_PER_CAPITA_STD_EM",
         "medicare_acute_care_payment" = "MGV_PER_CAPITA_STD_PA",
         "medicare_fqrc/rhc_payment" = "MGV_PER_CAPITA_STD_HC",
         "median_er_dist" = "POS_MEDIAN_DIST_ED",
         "median_surgery_dist" = "POS_MEDIAN_DIST_MEDSURG_ICU",
         "median_trauma_center_dist" = "POS_MEDIAN_DIST_TRAUMA",
         "median_pediatric_icu_dist" = "POS_MEDIAN_DIST_PED_ICU",
         "median_obstetrics_dist" = "POS_MEDIAN_DIST_OBSTETRICS",
         "median_health_clinic_dist" = "POS_MEDIAN_DIST_CLINIC",
         "median_drug_alcohol_care_dist" = "POS_MEDIAN_DIST_ALC"
  )
```

```{r chr feature cleaning 1}
# remove unwanted features
# convert principal care providers from per 100,000 people to per 1,000 people to match other data

chr_data <- all_chr_data %>%
  select(#"statecode","countycode",
    "fipscode", "state","county", #"year", "county_ranked", "v001_rawvalue", "v001_numerator", "v001_denominator", "v001_cilow", "v001_cihigh", "v001_flag", "v001_race_aian", "v001_race_aian_cilow", "v001_race_aian_cihigh", "v001_race_aian_flag", "v001_race_asian", "v001_race_asian_cilow", "v001_race_black", "v001_race_black_cilow", "v001_race_hispanic", "v001_race_hispanic_cilow", "v001_race_hispanic_cihigh", "v001_race_hispanic_flag", "v001_race_white", "v001_race_white_cilow", "v001_race_white_cihigh", "v001_race_white_flag", "v002_rawvalue", "v002_numerator", "v002_denominator", "v002_cilow", "v002_cihigh", "v036_rawvalue", "v036_numerator", "v036_denominator", "v036_cilow", "v036_cihigh",
 "v042_rawvalue", #"v042_numerator", "v042_denominator", "v042_cilow", "v042_cihigh",
 "v037_rawvalue", #"v037_numerator", "v037_denominator", "v037_cilow", "v037_cihigh", "v037_flag", "v037_race_aian", "v037_race_aian_cilow", "v037_race_aian_cihigh", "v037_race_asian", "v037_race_asian_cilow", "v037_race_asian_cihigh", "v037_race_black", "v037_race_black_cilow", "v037_race_black_cihigh", "v037_race_hispanic", "v037_race_hispanic_cilow", "v037_race_hispanic_cihigh", "v037_race_white", "v037_race_white_cilow", "v037_race_white_cihigh",
 "v009_rawvalue", #"v009_numerator", "v009_denominator", "v009_cilow", "v009_cihigh",
 "v011_rawvalue", #"v011_numerator", "v011_denominator", "v011_cilow", "v011_cihigh",
 "v133_rawvalue", #"v133_numerator", "v133_denominator", "v133_cilow", "v133_cihigh", 
 "v070_rawvalue", #"v070_numerator", "v070_denominator", "v070_cilow", "v070_cihigh", 
 "v132_rawvalue", #"v132_numerator", "v132_denominator", "v132_cilow", "v132_cihigh", 
 "v049_rawvalue", #"v049_numerator", "v049_denominator", "v049_cilow", "v049_cihigh", "v134_rawvalue", "v134_numerator", "v134_denominator", "v134_cilow", "v134_cihigh", "v045_rawvalue", "v045_numerator", "v045_denominator", "v045_cilow", "v045_cihigh", 
 "v014_rawvalue", #"v014_numerator", "v014_denominator", "v014_cilow", "v014_cihigh", "v014_race_aian", "v014_race_aian_cihigh", "v014_race_asian", "v014_race_asian_cilow", "v014_race_asian_cihigh", "v014_race_black", "v014_race_black_cilow", "v014_race_black_cihigh", "v014_race_hispanic", "v014_race_hispanic_cilow", "v014_race_hispanic_cihigh", "v014_race_white", "v014_race_white_cilow", "v014_race_white_cihigh",
 "v085_rawvalue", #"v085_numerator", "v085_denominator", "v085_cilow", "v085_cihigh", 
 "v004_rawvalue", #"v004_numerator", "v004_denominator", "v004_cilow", "v004_cihigh","v004_other_data_1", "v088_rawvalue", "v088_numerator", "v088_denominator", "v088_cilow", "v088_cihigh", "v088_other_data_1",
 "v062_rawvalue", #"v062_numerator", "v062_denominator", "v062_cilow", "v062_cihigh", "v062_other_data_1", 
 "v005_rawvalue", #"v005_numerator", "v005_denominator", "v005_cilow", "v005_cihigh", "v005_race_aian", "v005_race_asian", "v005_race_black", "v005_race_hispanic", "v005_race_white", 
 "v050_rawvalue", #"v050_numerator", "v050_denominator", "v050_cilow", "v050_cihigh", "v050_race_aian", "v050_race_asian", "v050_race_black", "v050_race_hispanic", "v050_race_white", 
 "v155_rawvalue", #"v155_numerator", "v155_denominator", "v155_cilow", "v155_cihigh", "v155_race_aian", "v155_race_asian", "v155_race_black", "v155_race_hispanic", "v155_race_white", 
 "v168_rawvalue", #"v168_numerator", "v168_denominator", "v168_cilow", "v168_cihigh", 
 "v069_rawvalue", #"v069_numerator", "v069_denominator", "v069_cilow", "v069_cihigh", 
 "v023_rawvalue", #"v023_numerator", "v023_denominator", "v023_cilow", "v023_cihigh",
 "v024_rawvalue", #"v024_numerator", "v024_denominator", "v024_cilow", "v024_cihigh", "v024_race_aian", "v024_race_aian_cilow", "v024_race_aian_cihigh", "v024_race_asian", "v024_race_asian_cilow", "v024_race_asian_cihigh", "v024_race_black", "v024_race_black_cilow", "v024_race_black_cihigh", "v024_race_hispanic", "v024_race_hispanic_cilow", "v024_race_hispanic_cihigh", "v024_race_white", "v024_race_white_cilow", "v024_race_white_cihigh", 
 "v044_rawvalue", #"v044_numerator", "v044_denominator", "v044_cilow", "v044_cihigh", "v082_rawvalue", "v082_numerator", "v082_denominator", "v082_cilow", "v082_cihigh", 
 "v140_rawvalue", #"v140_numerator", "v140_denominator", "v140_cilow", "v140_cihigh", 
 "v135_rawvalue", #"v135_numerator", "v135_denominator", "v135_cilow", "v135_cihigh", "v135_race_aian", "v135_race_aian_cilow", "v135_race_aian_cihigh", "v135_race_asian", "v135_race_asian_cilow", "v135_race_asian_cihigh", "v135_race_black", "v135_race_black_cilow", "v135_race_black_cihigh", "v135_race_hispanic" , "v135_race_hispanic_cilow", "v135_race_hispanic_cihigh", "v135_race_white", "v135_race_white_cilow", "v135_race_white_cihigh", 
 "v125_rawvalue", #"v125_numerator", "v125_denominator", "v125_cilow", "v125_cihigh", 
 "v124_rawvalue", #"v124_numerator", "v124_denominator", "v124_cilow", "v124_cihigh", "v136_rawvalue", "v136_numerator", "v136_denominator", "v136_cilow", "v136_cihigh", 
 "v136_other_data_1", #"v136_other_data_1_cilow", "v136_other_data_1_cihigh",
 "v136_other_data_2", #"v136_other_data_2_cilow", "v136_other_data_2_cihigh", 
 "v136_other_data_3", #"v136_other_data_3_cilow", "v136_other_data_3_cihigh", "v067_rawvalue", "v067_numerator", "v067_denominator", "v067_cilow", "v067_cihigh", "v067_race_aian", "v067_race_aian_cilow", "v067_race_aian_cihigh", "v067_race_asian", "v067_race_asian_cilow", "v067_race_asian_cihigh", "v067_race_black", "v067_race_black_cilow", "v067_race_black_cihigh", "v067_race_hispanic", "v067_race_hispanic_cilow", "v067_race_hispanic_cihigh", "v067_race_white", "v067_race_white_cilow", "v067_race_white_cihigh", "v137_rawvalue", "v137_numerator", "v137_denominator", "v137_cilow", "v137_cihigh", 
 "v147_rawvalue", #"v147_numerator", "v147_denominator", "v147_cilow", "v147_cihigh", "v147_race_aian", "v147_race_aian_cilow", "v147_race_aian_cihigh", "v147_race_asian", "v147_race_asian_cilow", "v147_race_asian_cihigh", "v147_race_black", "v147_race_black_cilow", "v147_race_black_cihigh", "v147_race_hispanic", "v147_race_hispanic_cilow", "v147_race_hispanic_cihigh", "v147_race_white", "v147_race_white_cilow", "v147_race_white_cihigh", 
 "v127_rawvalue", #"v127_numerator", "v127_denominator", "v127_cilow", "v127_cihigh", "v127_race_aian", "v127_race_aian_cilow", "v127_race_aian_cihigh", "v127_race_asian", "v127_race_asian_cilow", "v127_race_asian_cihigh", "v127_race_black", "v127_race_black_cilow", "v127_race_black_cihigh", "v127_race_hispanic", "v127_race_hispanic_cilow", "v127_race_hispanic_cihigh", "v127_race_white", "v127_race_white_cilow", "v127_race_white_cihigh", 
 "v128_rawvalue", #"v128_numerator", "v128_denominator", "v128_cilow", "v128_cihigh", "v128_race_aian", "v128_race_aian_cilow", "v128_race_aian_cihigh", "v128_race_asian", "v128_race_asian_cilow", "v128_race_asian_cihigh", "v128_race_black", "v128_race_black_cilow", "v128_race_black_cihigh", "v128_race_hispanic", "v128_race_hispanic_cilow", "v128_race_hispanic_cihigh", "v128_race_white", "v128_race_white_cilow", "v128_race_white_cihigh", 
 "v129_rawvalue", #"v129_numerator", "v129_denominator", "v129_cilow", "v129_cihigh", "v129_race_aian", "v129_race_aian_cilow", "v129_race_aian_cihigh", "v129_race_asian", "v129_race_asian_cilow","v129_race_asian_cihigh", "v129_race_black", "v129_race_black_cilow", "v129_race_black_cihigh", "v129_race_hispanic", "v129_race_hispanic_cilow", "v129_race_hispanic_cihigh", "v129_race_white", "v129_race_white_cilow", "v129_race_white_cihigh", 
 "v144_rawvalue", #"v144_numerator", "v144_denominator", "v144_cilow", "v144_cihigh", "v145_rawvalue", "v145_numerator", "v145_denominator", "v145_cilow", "v145_cihigh", 
 "v060_rawvalue", #"v060_numerator", "v060_denominator", "v060_cilow", "v060_cihigh", 
 "v061_rawvalue", #"v061_numerator", "v061_denominator", "v061_cilow", "v061_cihigh", 
 "v139_rawvalue", #"v139_numerator", "v139_denominator", "v139_cilow", "v139_cihigh", "v083_rawvalue", "v083_numerator", "v083_denominator", "v083_cilow", "v083_cihigh", 
 "v138_rawvalue", #"v138_numerator", "v138_denominator", "v138_cilow", "v138_cihigh", "v138_race_aian", "v138_race_aian_cilow", "v138_race_aian_cihigh", "v138_race_asian", "v138_race_asian_cilow", "v138_race_asian_cihigh", "v138_race_black", "v138_race_black_cilow", "v138_race_black_cihigh", "v138_race_hispanic", "v138_race_hispanic_cilow", "v138_race_hispanic_cihigh", "v138_race_white", "v138_race_white_cilow", "v138_race_white_cihigh", 
 "v143_rawvalue", #"v143_numerator", "v143_denominator", "v143_cilow", "v143_cihigh", "v003_rawvalue", "v003_numerator", "v003_denominator", "v003_cilow", "v003_cihigh", "v122_rawvalue", "v122_numerator", "v122_denominator", "v122_cilow", "v122_cihigh", "v131_rawvalue", "v131_numerator, "v131_denominator", "v131_cilow", "v131_cihigh", "v131_other_data_1", 
 "v021_rawvalue", #"v021_numerator", "v021_denominator", "v021_cilow", "v021_cihigh", 
 "v149_rawvalue", #"v149_numerator", "v149_denominator", "v149_cilow", "v149_cihigh", 
 "v159_rawvalue", #"v159_numerator", "v159_denominator", "v159_cilow", "v159_cihigh", "v159_race_aian", "v159_race_asian", "v159_race_black", "v159_race_hispanic", "v159_race_white", 
 "v160_rawvalue", #"v160_numerator", "v160_denominator", "v160_cilow", "v160_cihigh", "v160_race_aian", "v160_race_asian", "v160_race_black", "v160_race_hispanic", "v160_race_white", 
 "v167_rawvalue", #"v167_numerator", "v167_denominator", "v167_cilow", "v167_cihigh", 
 "v169_rawvalue", #"v169_numerator", "v169_denominator", "v169_cilow", "v169_cihigh", 
 "v151_rawvalue", #"v151_numerator", "v151_denominator", "v151_cilow", "v151_cihigh", 
 "v063_rawvalue", #"v063_numerator", "v063_denominator", "v063_cilow", "v063_cihigh", "v063_race_aian", "v063_race_aian_cilow", "v063_race_aian_cihigh", "v063_race_asian", "v063_race_asian_cilow", "v063_race_asian_cihigh", "v063_race_black", "v063_race_black_cilow", "v063_race_black_cihigh", "v063_race_hispanic", "v063_race_hispanic_cilow", "v063_race_hispanic_cihigh", "v063_race_white", "v063_race_white_cilow", "v063_race_white_cihigh", 
 "v170_rawvalue", #"v170_numerator", "v170_denominator", "v170_cilow", "v170_cihigh", 
 "v065_rawvalue", #"v065_numerator", "v065_denominator", "v065_cilow", "v065_cihigh", 
 "v141_rawvalue", #"v141_numerator", "v141_denominator", "v141_cilow", "v141_cihigh", 
 "v171_rawvalue", #"v171_numerator", "v171_denominator", "v171_cilow", "v171_cihigh", "v172_rawvalue", "v172_numerator", "v172_denominator", "v172_cilow", "v172_cihigh", 
 "v015_rawvalue", #"v015_numerator", "v015_denominator", "v015_cilow", "v015_cihigh", "v015_race_aian", "v015_race_aian_cilow", "v015_race_aian_cihigh", "v015_race_asian", "v015_race_asian_cilow", "v015_race_asian_cihigh", "v015_race_black", "v015_race_black_cilow", "v015_race_black_cihigh", "v015_race_hispanic", "v015_race_hispanic_cilow", "v015_race_hispanic_cihigh", "v015_race_white", "v015_race_white_cilow", "v015_race_white_cihigh",
 "v161_rawvalue", #"v161_numerator", "v161_denominator", "v161_cilow", "v161_cihigh", "v161_other_data_1", "v161_race_aian", "v161_race_aian_cilow", "v161_race_aian_cihigh", "v161_race_asian", "v161_race_asian_cilow", "v161_race_asian_cihigh", "v161_race_black", "v161_race_black_cilow", "v161_race_black_cihigh", "v161_race_hispanic", "v161_race_hispanic_cilow", "v161_race_hispanic_cihigh", "v161_race_white", "v161_race_white_cilow", "v161_race_white_cihigh", 
 "v148_rawvalue", #"v148_numerator", "v148_denominator", "v148_cilow", "v148_cihigh", "v148_race_aian", "v148_race_aian_cilow", "v148_race_aian_cihigh", "v148_race_asian", "v148_race_asian_cilow", "v148_race_asian_cihigh", "v148_race_black", "v148_race_black_cilow", "v148_race_black_cihigh", "v148_race_hispanic", "v148_race_hispanic_cilow", "v148_race_hispanic_cihigh", "v148_race_white", "v148_race_white_cilow", "v148_race_white_cihigh", "v039_rawvalue", "v039_numerator", "v039_denominator", "v039_cilow", "v039_cihigh", "v039_race_aian", "v039_race_aian_cilow", "v039_race_aian_cihigh", "v039_race_asian", "v039_race_asian_cilow", "v039_race_asian_cihigh", "v039_race_black", "v039_race_black_cilow", "v039_race_black_cihigh", "v039_race_hispanic", "v039_race_hispanic_cilow", "v039_race_hispanic_cihigh", "v039_race_white", "v039_race_white_cilow", "v039_race_white_cihigh", 
 "v158_rawvalue", #"v158_numerator", "v158_denominator", "v158_cilow", "v158_cihigh", "v158_other_data_1", "v158_other_data_2", 
 "v177_rawvalue", #"v177_numerator", "v177_denominator", "v177_cilow", "v177_cihigh", "v178_rawvalue", "v178_numerator", "v178_denominator", "v178_cilow", "v178_cihigh", 
 "v156_rawvalue", #"v156_numerator", "v156_denominator", "v156_cilow", "v156_cihigh", "v153_rawvalue", 
 "v153_numerator", #"v153_denominator", "v153_cilow", "v153_cihigh", "v154_rawvalue", "v154_numerator", "v154_denominator", "v154_cilow", "v154_cihigh", "v166_rawvalue", "v166_numerator", "v166_denominator", "v166_cilow", "v166_cihigh", "v051_rawvalue", "v051_numerator", "v051_denominator", "v051_cilow", "v051_cihigh", 
 "v052_rawvalue", #"v052_numerator", "v052_denominator", "v052_cilow", "v052_cihigh", 
 "v053_rawvalue", #"v053_numerator", "v053_denominator", "v053_cilow", "v053_cihigh", "v054_rawvalue", "v054_numerator", "v054_denominator", "v054_cilow", "v054_cihigh", "v055_rawvalue", "v055_numerator", "v055_denominator", "v055_cilow", "v055_cihigh", "v081_rawvalue", "v081_numerator", "v081_denominator", "v081_cilow", "v081_cihigh", "v080_rawvalue", "v080_numerator" , "v080_denominator", "v080_cilow", "v080_cihigh", "v056_rawvalue", "v056_numerator", "v056_denominator", "v056_cilow", "v056_cihigh", "v126_rawvalue", "v126_numerator", "v126_denominator", "v126_cilow", "v126_cihigh", "v059_rawvalue", "v059_numerator", "v059_denominator", "v059_cilow", "v059_cihigh", "v057_rawvalue", "v057_numerator", "v057_denominator", "v057_cilow", "v057_cihigh", 
 "v058_rawvalue", #"v058_numerator", "v058_denominator", "v058_cilow", "v058_cihigh"
  ) %>% 
  mutate(pcp_pt = v004_rawvalue/100) %>% 
  select(-v004_rawvalue)
```

```{r chr feature renaming}
chr_data <- chr_data %>% 
  rename("fips_code" = "fipscode",
         "state" =  "state", 
         "county"  ="county",  
         "poor_menatal_health" = "v042_rawvalue",
         "pct_low_birthweight" = "v037_rawvalue",
         "pct_adult_smokers" = "v009_rawvalue",
         "pct_obese_adults" = "v011_rawvalue",
         "food_enviroment_1:10_bad:good" = "v133_rawvalue",
         "pct_no_exercise" = "v070_rawvalue",
         "pct_access_to_exercise" = "v132_rawvalue",
         "pct_binge_drinkers" = "v049_rawvalue",
         "teen_births_prk_1k" = "v014_rawvalue",
         "pct_under_65_no_health_insurance" = "v085_rawvalue",
         "hospital_stay_per_100k" = "v005_rawvalue",
         "pct_elderly_mmmograms" = "v050_rawvalue",
         "pct_flu_vaccines_billed" = "v155_rawvalue",
         "pct_highschool_diploma" = "v168_rawvalue",
         "pct_some_college" = "v069_rawvalue",
         "pct_unemployed" = "v023_rawvalue",
         "pct_adult_poverty" = "v024_rawvalue",
         "inequality_ratio" = "v044_rawvalue",
         "social_clubs_per_10k" = "v140_rawvalue",
         "injury_death_rate_per_100k" = "v135_rawvalue",
         "air_polution_metric" =  "v125_rawvalue",
         "water_0:1_bad_good" = "v124_rawvalue",
         "pct_high_housing_costs" = "v136_other_data_1",
         "pct_overcrowded_hh" = "v136_other_data_2",
         "pct_no_kitchen_or_plumbinmg" = "v136_other_data_3",
         "life_expectancy_years" = "v147_rawvalue",
         "premature_deaths_per_100k" = "v127_rawvalue",
         "underage_deaths_per_100k" = "v128_rawvalue",
         "infant_deaths_per_1k_births" = "v129_rawvalue",
         "pct_poor_health" = "v144_rawvalue",
         "pct_diabetes" =  "v060_rawvalue",
         "pct_hiv" = "v061_rawvalue",
         "pct_food_insecurities" = "v139_rawvalue",
         "drug_overdose_per_100k" = "v138_rawvalue",
         "pct_insufficie" = "v143_rawvalue",
         "pct_on_time_hs_graduation" = "v021_rawvalue",
         "pct_disconnected_youth" = "v149_rawvalue",
         "children_reading_score" = "v159_rawvalue",
         "children_math_score" = "v160_rawvalue",
         "school_segregation_0:1__low:high" = "v167_rawvalue",
         "school_funding_gap" = "v169_rawvalue",
         "women_to_man_pay_ratio" = "v151_rawvalue",
         "median_hh_income" = "v063_rawvalue",
         "hourly_living_wage" = "v170_rawvalue",
         "children_eligible_for_lunch" = "v065_rawvalue",
         "black_white_segregation" = "v141_rawvalue",
         "pct_income_to_childcare" = "v171_rawvalue",
         "homicides_per_100k" = "v015_rawvalue",
         "suicides_per_100k" = "v161_rawvalue",
         "firearm_fatalities_per_100k" = "v148_rawvalue",
         "juvenile_arrests_per_1k" = "v158_rawvalue",
         "pct_voters" = "v177_rawvalue",
         "traffic_per_meter" = "v156_rawvalue",
         "pct_home_owner" = "v153_numerator",
         "pct_0_17_age" = "v052_rawvalue",
         "pct_18_65_age" = "v053_rawvalue",
         "pct_rural_population" = "v058_rawvalue",    
  )
```





$$Data Exploration$$

```{r}
names(chr_data)

```
```{r}
names(sdoh_data)
```




















































































































































































